# ConfigMap for API URLs
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-urls
data:
  VITE_AUTH_API_URL: "http://district12.xyz/auth"
  VITE_PAYMENT_API_URL: "http://district12.xyz/pay"
  VITE_DOWNLOAD_API_URL: "http://district12.xyz/down"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  RABBITMQ_PORT: "5672"
---
# auth-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-service
          image: ishrakadit07/auth_service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: mongo-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: mongo-password
            - name: MONGODB_CLUSTER_NAME
              value: "cluster-for-ishrak"
            - name: MONGODB_APP_NAME
              value: "cluster-for-ishrak"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: REDIS_PORT
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: RABBITMQ_URL
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: RABBITMQ_PORT
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# auth-service Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
# payment-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment-service
          image: ishrakadit07/payment_service
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: VITE_AUTH_API_URL
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: mongo-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: mongo-password
            - name: MONGODB_CLUSTER_NAME
              value: "cluster-for-ishrak"
            - name: MONGODB_APP_NAME
              value: "cluster-for-ishrak"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: REDIS_PORT
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: RABBITMQ_URL
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: RABBITMQ_PORT
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# payment-service Service
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
# download-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: download
    spec:
      containers:
        - name: download-service
          image: ishrakadit07/download_service
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: VITE_AUTH_API_URL
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: mongo-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-atlas-secret
                  key: mongo-password
            - name: MONGODB_CLUSTER_NAME
              value: "cluster-for-ishrak"
            - name: MONGODB_APP_NAME
              value: "cluster-for-ishrak"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: REDIS_PORT
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: RABBITMQ_URL
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: RABBITMQ_PORT
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# download-service Service
apiVersion: v1
kind: Service
metadata:
  name: download-service
spec:
  selector:
    app: download
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
---
# client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ishrakadit07/project_web
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: VITE_AUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: VITE_AUTH_API_URL
            - name: VITE_PAYMENT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: VITE_PAYMENT_API_URL
            - name: VITE_DOWNLOAD_API_URL
              valueFrom:
                configMapKeyRef:
                  name: api-urls
                  key: VITE_DOWNLOAD_API_URL
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# client Service
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: ClusterIP
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
  selector:
    app: client
--- 
# Horizontal Pod Autoscaler for auth-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
# Horizontal Pod Autoscaler for payment-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
# Horizontal Pod Autoscaler for download-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: download-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: download-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
# Horizontal Pod Autoscaler for client
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80