apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
config:
  origins: "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - HEAD
    - OPTIONS
  headers:
    - Content-Type
    - Authorization
  credentials: true
plugin: cors