# Auth Service VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-vs
spec:
  hosts:
  - "auth-service.default.svc.cluster.local"
  http:
  - match:
    - uri:
        prefix: "/auth"
    route:
    - destination:
        host: auth-service
        port:
          number: 8000
---
# Payment Service VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payment-vs
spec:
  hosts:
  - "payment-service.default.svc.cluster.local"
  http:
  - match:
    - uri:
        prefix: "/pay"
    route:
    - destination:
        host: payment-service
        port:
          number: 8001
---
# Download Service VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: download-vs
spec:
  hosts:
  - "download-service.default.svc.cluster.local"
  http:
  - match:
    - uri:
        prefix: "/down"
    route:
    - destination:
        host: download-service
        port:
          number: 8002