apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: auth-ingress-config
upstream:
  hash_on: header
  hash_fallback: cookie

---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: payment-ingress-config
upstream:
  hash_on: header
  hash_fallback: cookie
  # connect_timeout: 60000  # Time in milliseconds
  # read_timeout: 60000
  # send_timeout: 60000
  # retries: 2

---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: download-ingress-config
upstream:
  hash_on: header
  hash_fallback: cookie