services:
  web:
    depends_on:
      - auth-service
      - payment-service
    build: ./client
    ports: 
      - 5173:5173
    environment:
      VITE_AUTH_API_URL: http://localhost:8000
      VITE_PAYMENT_API_URL: http://localhost:8001
      VITE_DOWNLOAD_API_URL: http://localhost:8002
    networks:
      - dfsa-network
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync
          
  auth-service:
    depends_on:
      redis:
        condition: service_started
    build: ./auth_service
    ports: 
      - 8000:8000
    environment:
      PAYMENT_SERVICE_URL: http://payment-service:8001
      DOWNLOAD_SERVICE_URL: http://download-service:8002
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - dfsa-network
    develop:
      watch:
        - path: ./auth_service/package.json
          action: rebuild
        - path: ./auth_service/package-lock.json
          action: rebuild
        - path: ./auth_service
          target: /app
          action: sync

  payment-service:
    depends_on:
      redis:
        condition: service_started
    build: ./payment_service
    ports: 
      - 8001:8001
    environment:
      AUTH_SERVICE_URL: http://auth-service:8000
      DOWNLOAD_SERVICE_URL: http://download-service:8002
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - dfsa-network
    develop:
      watch:
        - path: ./payment_service/package.json
          action: rebuild
        - path: ./payment_service/package-lock.json
          action: rebuild
        - path: ./payment_service
          target: /app
          action: sync

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - dfsa-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  dfsa-network:
    driver: bridge