# ConfigMap for API URLs and Redis/Database Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-config
data:
  VITE_AUTH_API_URL: "https://district12.xyz/auth"
  VITE_PAYMENT_API_URL: "https://district12.xyz/pay"
  VITE_DOWNLOAD_API_URL: "https://district12.xyz/down"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "template-pg-do-user-18003520-0.g.db.ondigitalocean.com"
  POSTGRES_PORT: "25060"
  POSTGRES_DB: "defaultdb"
  POSTGRES_USER: "doadmin"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: QVZOU19XdW5kSDhpM2hIdFZJblRLZFhr
---
# auth-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploypg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authpg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: authpg
    spec:
      containers:
        - name: auth-servicepg
          image: ishrakadit07/auth_servicepg
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: template-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# auth-service Service
apiVersion: v1
kind: Service
metadata:
  name: auth-servicepg
spec:
  selector:
    app: authpg
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
# payment-service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deploypg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentpg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: paymentpg
    spec:
      containers:
        - name: payment-servicepg
          image: ishrakadit07/payment_servicepg
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: template-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# payment-service Service
apiVersion: v1
kind: Service
metadata:
  name: payment-servicepg
spec:
  selector:
    app: paymentpg
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
# client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploypg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientpg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: clientpg
    spec:
      containers:
        - name: clientpg
          image: ishrakadit07/project_web
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: template-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
# client Service
apiVersion: v1
kind: Service
metadata:
  name: client-servicepg
spec:
  type: ClusterIP
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
  selector:
    app: clientpg
