apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine  # RabbitMQ image with the management plugin
        ports:
        - containerPort: 5672   # AMQP port for client connections
        - containerPort: 15672  # Management UI port
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          value: "adminpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 5672    # Port for AMQP protocol
    targetPort: 5672
    name: amqp
  - port: 15672   # Port for RabbitMQ Management UI
    targetPort: 15672
    name: management
  selector:
    app: rabbitmq