apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 3  # Number of master nodes
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        command:
          - "redis-server"
          - "--cluster-enabled"
          - "yes"
          - "--cluster-config-file"
          - "/data/nodes.conf"
          - "--cluster-node-timeout"
          - "5000"
          - "--appendonly"
          - "yes"
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 6379
  selector:
    app: redis